# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/itziar/dev/engine2d

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/itziar/dev/engine2d

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/itziar/dev/engine2d/CMakeFiles /home/itziar/dev/engine2d//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/itziar/dev/engine2d/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/itziar/dev/engine2d/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lua_static

# Build rule for target.
lua_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lua_static
.PHONY : lua_static

# fast build rule for target.
lua_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/build
.PHONY : lua_static/fast

#=============================================================================
# Target rules for targets named 2d-engine

# Build rule for target.
2d-engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 2d-engine
.PHONY : 2d-engine

# fast build rule for target.
2d-engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/build
.PHONY : 2d-engine/fast

#=============================================================================
# Target rules for targets named SDL3-shared

# Build rule for target.
SDL3-shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3-shared
.PHONY : SDL3-shared

# fast build rule for target.
SDL3-shared/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl3-build/CMakeFiles/SDL3-shared.dir/build.make _deps/sdl3-build/CMakeFiles/SDL3-shared.dir/build
.PHONY : SDL3-shared/fast

#=============================================================================
# Target rules for targets named SDL3_test

# Build rule for target.
SDL3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3_test
.PHONY : SDL3_test

# fast build rule for target.
SDL3_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl3-build/CMakeFiles/SDL3_test.dir/build.make _deps/sdl3-build/CMakeFiles/SDL3_test.dir/build
.PHONY : SDL3_test/fast

#=============================================================================
# Target rules for targets named SDL_uclibc

# Build rule for target.
SDL_uclibc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL_uclibc
.PHONY : SDL_uclibc

# fast build rule for target.
SDL_uclibc/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl3-build/CMakeFiles/SDL_uclibc.dir/build.make _deps/sdl3-build/CMakeFiles/SDL_uclibc.dir/build
.PHONY : SDL_uclibc/fast

#=============================================================================
# Target rules for targets named glm

# Build rule for target.
glm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glm
.PHONY : glm

# fast build rule for target.
glm/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glm-build/glm/CMakeFiles/glm.dir/build.make _deps/glm-build/glm/CMakeFiles/glm.dir/build
.PHONY : glm/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/Experimental.dir/build.make _deps/sol2-build/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/Nightly.dir/build.make _deps/sol2-build/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/Continuous.dir/build.make _deps/sol2-build/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/NightlyMemoryCheck.dir/build.make _deps/sol2-build/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/NightlyStart.dir/build.make _deps/sol2-build/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/NightlyUpdate.dir/build.make _deps/sol2-build/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/NightlyConfigure.dir/build.make _deps/sol2-build/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/NightlyBuild.dir/build.make _deps/sol2-build/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/NightlyTest.dir/build.make _deps/sol2-build/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/NightlyCoverage.dir/build.make _deps/sol2-build/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/NightlyMemCheck.dir/build.make _deps/sol2-build/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/NightlySubmit.dir/build.make _deps/sol2-build/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ExperimentalStart.dir/build.make _deps/sol2-build/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ExperimentalUpdate.dir/build.make _deps/sol2-build/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ExperimentalConfigure.dir/build.make _deps/sol2-build/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ExperimentalBuild.dir/build.make _deps/sol2-build/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ExperimentalTest.dir/build.make _deps/sol2-build/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ExperimentalCoverage.dir/build.make _deps/sol2-build/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ExperimentalMemCheck.dir/build.make _deps/sol2-build/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ExperimentalSubmit.dir/build.make _deps/sol2-build/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ContinuousStart.dir/build.make _deps/sol2-build/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ContinuousUpdate.dir/build.make _deps/sol2-build/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ContinuousConfigure.dir/build.make _deps/sol2-build/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ContinuousBuild.dir/build.make _deps/sol2-build/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ContinuousTest.dir/build.make _deps/sol2-build/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ContinuousCoverage.dir/build.make _deps/sol2-build/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ContinuousMemCheck.dir/build.make _deps/sol2-build/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sol2-build/CMakeFiles/ContinuousSubmit.dir/build.make _deps/sol2-build/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

_deps/lua-src/lapi.o: _deps/lua-src/lapi.c.o
.PHONY : _deps/lua-src/lapi.o

# target to build an object file
_deps/lua-src/lapi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lapi.c.o
.PHONY : _deps/lua-src/lapi.c.o

_deps/lua-src/lapi.i: _deps/lua-src/lapi.c.i
.PHONY : _deps/lua-src/lapi.i

# target to preprocess a source file
_deps/lua-src/lapi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lapi.c.i
.PHONY : _deps/lua-src/lapi.c.i

_deps/lua-src/lapi.s: _deps/lua-src/lapi.c.s
.PHONY : _deps/lua-src/lapi.s

# target to generate assembly for a file
_deps/lua-src/lapi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lapi.c.s
.PHONY : _deps/lua-src/lapi.c.s

_deps/lua-src/lauxlib.o: _deps/lua-src/lauxlib.c.o
.PHONY : _deps/lua-src/lauxlib.o

# target to build an object file
_deps/lua-src/lauxlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lauxlib.c.o
.PHONY : _deps/lua-src/lauxlib.c.o

_deps/lua-src/lauxlib.i: _deps/lua-src/lauxlib.c.i
.PHONY : _deps/lua-src/lauxlib.i

# target to preprocess a source file
_deps/lua-src/lauxlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lauxlib.c.i
.PHONY : _deps/lua-src/lauxlib.c.i

_deps/lua-src/lauxlib.s: _deps/lua-src/lauxlib.c.s
.PHONY : _deps/lua-src/lauxlib.s

# target to generate assembly for a file
_deps/lua-src/lauxlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lauxlib.c.s
.PHONY : _deps/lua-src/lauxlib.c.s

_deps/lua-src/lbaselib.o: _deps/lua-src/lbaselib.c.o
.PHONY : _deps/lua-src/lbaselib.o

# target to build an object file
_deps/lua-src/lbaselib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lbaselib.c.o
.PHONY : _deps/lua-src/lbaselib.c.o

_deps/lua-src/lbaselib.i: _deps/lua-src/lbaselib.c.i
.PHONY : _deps/lua-src/lbaselib.i

# target to preprocess a source file
_deps/lua-src/lbaselib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lbaselib.c.i
.PHONY : _deps/lua-src/lbaselib.c.i

_deps/lua-src/lbaselib.s: _deps/lua-src/lbaselib.c.s
.PHONY : _deps/lua-src/lbaselib.s

# target to generate assembly for a file
_deps/lua-src/lbaselib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lbaselib.c.s
.PHONY : _deps/lua-src/lbaselib.c.s

_deps/lua-src/lcode.o: _deps/lua-src/lcode.c.o
.PHONY : _deps/lua-src/lcode.o

# target to build an object file
_deps/lua-src/lcode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lcode.c.o
.PHONY : _deps/lua-src/lcode.c.o

_deps/lua-src/lcode.i: _deps/lua-src/lcode.c.i
.PHONY : _deps/lua-src/lcode.i

# target to preprocess a source file
_deps/lua-src/lcode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lcode.c.i
.PHONY : _deps/lua-src/lcode.c.i

_deps/lua-src/lcode.s: _deps/lua-src/lcode.c.s
.PHONY : _deps/lua-src/lcode.s

# target to generate assembly for a file
_deps/lua-src/lcode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lcode.c.s
.PHONY : _deps/lua-src/lcode.c.s

_deps/lua-src/lcorolib.o: _deps/lua-src/lcorolib.c.o
.PHONY : _deps/lua-src/lcorolib.o

# target to build an object file
_deps/lua-src/lcorolib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lcorolib.c.o
.PHONY : _deps/lua-src/lcorolib.c.o

_deps/lua-src/lcorolib.i: _deps/lua-src/lcorolib.c.i
.PHONY : _deps/lua-src/lcorolib.i

# target to preprocess a source file
_deps/lua-src/lcorolib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lcorolib.c.i
.PHONY : _deps/lua-src/lcorolib.c.i

_deps/lua-src/lcorolib.s: _deps/lua-src/lcorolib.c.s
.PHONY : _deps/lua-src/lcorolib.s

# target to generate assembly for a file
_deps/lua-src/lcorolib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lcorolib.c.s
.PHONY : _deps/lua-src/lcorolib.c.s

_deps/lua-src/lctype.o: _deps/lua-src/lctype.c.o
.PHONY : _deps/lua-src/lctype.o

# target to build an object file
_deps/lua-src/lctype.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lctype.c.o
.PHONY : _deps/lua-src/lctype.c.o

_deps/lua-src/lctype.i: _deps/lua-src/lctype.c.i
.PHONY : _deps/lua-src/lctype.i

# target to preprocess a source file
_deps/lua-src/lctype.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lctype.c.i
.PHONY : _deps/lua-src/lctype.c.i

_deps/lua-src/lctype.s: _deps/lua-src/lctype.c.s
.PHONY : _deps/lua-src/lctype.s

# target to generate assembly for a file
_deps/lua-src/lctype.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lctype.c.s
.PHONY : _deps/lua-src/lctype.c.s

_deps/lua-src/ldblib.o: _deps/lua-src/ldblib.c.o
.PHONY : _deps/lua-src/ldblib.o

# target to build an object file
_deps/lua-src/ldblib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ldblib.c.o
.PHONY : _deps/lua-src/ldblib.c.o

_deps/lua-src/ldblib.i: _deps/lua-src/ldblib.c.i
.PHONY : _deps/lua-src/ldblib.i

# target to preprocess a source file
_deps/lua-src/ldblib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ldblib.c.i
.PHONY : _deps/lua-src/ldblib.c.i

_deps/lua-src/ldblib.s: _deps/lua-src/ldblib.c.s
.PHONY : _deps/lua-src/ldblib.s

# target to generate assembly for a file
_deps/lua-src/ldblib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ldblib.c.s
.PHONY : _deps/lua-src/ldblib.c.s

_deps/lua-src/ldebug.o: _deps/lua-src/ldebug.c.o
.PHONY : _deps/lua-src/ldebug.o

# target to build an object file
_deps/lua-src/ldebug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ldebug.c.o
.PHONY : _deps/lua-src/ldebug.c.o

_deps/lua-src/ldebug.i: _deps/lua-src/ldebug.c.i
.PHONY : _deps/lua-src/ldebug.i

# target to preprocess a source file
_deps/lua-src/ldebug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ldebug.c.i
.PHONY : _deps/lua-src/ldebug.c.i

_deps/lua-src/ldebug.s: _deps/lua-src/ldebug.c.s
.PHONY : _deps/lua-src/ldebug.s

# target to generate assembly for a file
_deps/lua-src/ldebug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ldebug.c.s
.PHONY : _deps/lua-src/ldebug.c.s

_deps/lua-src/ldo.o: _deps/lua-src/ldo.c.o
.PHONY : _deps/lua-src/ldo.o

# target to build an object file
_deps/lua-src/ldo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ldo.c.o
.PHONY : _deps/lua-src/ldo.c.o

_deps/lua-src/ldo.i: _deps/lua-src/ldo.c.i
.PHONY : _deps/lua-src/ldo.i

# target to preprocess a source file
_deps/lua-src/ldo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ldo.c.i
.PHONY : _deps/lua-src/ldo.c.i

_deps/lua-src/ldo.s: _deps/lua-src/ldo.c.s
.PHONY : _deps/lua-src/ldo.s

# target to generate assembly for a file
_deps/lua-src/ldo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ldo.c.s
.PHONY : _deps/lua-src/ldo.c.s

_deps/lua-src/ldump.o: _deps/lua-src/ldump.c.o
.PHONY : _deps/lua-src/ldump.o

# target to build an object file
_deps/lua-src/ldump.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ldump.c.o
.PHONY : _deps/lua-src/ldump.c.o

_deps/lua-src/ldump.i: _deps/lua-src/ldump.c.i
.PHONY : _deps/lua-src/ldump.i

# target to preprocess a source file
_deps/lua-src/ldump.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ldump.c.i
.PHONY : _deps/lua-src/ldump.c.i

_deps/lua-src/ldump.s: _deps/lua-src/ldump.c.s
.PHONY : _deps/lua-src/ldump.s

# target to generate assembly for a file
_deps/lua-src/ldump.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ldump.c.s
.PHONY : _deps/lua-src/ldump.c.s

_deps/lua-src/lfunc.o: _deps/lua-src/lfunc.c.o
.PHONY : _deps/lua-src/lfunc.o

# target to build an object file
_deps/lua-src/lfunc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lfunc.c.o
.PHONY : _deps/lua-src/lfunc.c.o

_deps/lua-src/lfunc.i: _deps/lua-src/lfunc.c.i
.PHONY : _deps/lua-src/lfunc.i

# target to preprocess a source file
_deps/lua-src/lfunc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lfunc.c.i
.PHONY : _deps/lua-src/lfunc.c.i

_deps/lua-src/lfunc.s: _deps/lua-src/lfunc.c.s
.PHONY : _deps/lua-src/lfunc.s

# target to generate assembly for a file
_deps/lua-src/lfunc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lfunc.c.s
.PHONY : _deps/lua-src/lfunc.c.s

_deps/lua-src/lgc.o: _deps/lua-src/lgc.c.o
.PHONY : _deps/lua-src/lgc.o

# target to build an object file
_deps/lua-src/lgc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lgc.c.o
.PHONY : _deps/lua-src/lgc.c.o

_deps/lua-src/lgc.i: _deps/lua-src/lgc.c.i
.PHONY : _deps/lua-src/lgc.i

# target to preprocess a source file
_deps/lua-src/lgc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lgc.c.i
.PHONY : _deps/lua-src/lgc.c.i

_deps/lua-src/lgc.s: _deps/lua-src/lgc.c.s
.PHONY : _deps/lua-src/lgc.s

# target to generate assembly for a file
_deps/lua-src/lgc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lgc.c.s
.PHONY : _deps/lua-src/lgc.c.s

_deps/lua-src/linit.o: _deps/lua-src/linit.c.o
.PHONY : _deps/lua-src/linit.o

# target to build an object file
_deps/lua-src/linit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/linit.c.o
.PHONY : _deps/lua-src/linit.c.o

_deps/lua-src/linit.i: _deps/lua-src/linit.c.i
.PHONY : _deps/lua-src/linit.i

# target to preprocess a source file
_deps/lua-src/linit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/linit.c.i
.PHONY : _deps/lua-src/linit.c.i

_deps/lua-src/linit.s: _deps/lua-src/linit.c.s
.PHONY : _deps/lua-src/linit.s

# target to generate assembly for a file
_deps/lua-src/linit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/linit.c.s
.PHONY : _deps/lua-src/linit.c.s

_deps/lua-src/liolib.o: _deps/lua-src/liolib.c.o
.PHONY : _deps/lua-src/liolib.o

# target to build an object file
_deps/lua-src/liolib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/liolib.c.o
.PHONY : _deps/lua-src/liolib.c.o

_deps/lua-src/liolib.i: _deps/lua-src/liolib.c.i
.PHONY : _deps/lua-src/liolib.i

# target to preprocess a source file
_deps/lua-src/liolib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/liolib.c.i
.PHONY : _deps/lua-src/liolib.c.i

_deps/lua-src/liolib.s: _deps/lua-src/liolib.c.s
.PHONY : _deps/lua-src/liolib.s

# target to generate assembly for a file
_deps/lua-src/liolib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/liolib.c.s
.PHONY : _deps/lua-src/liolib.c.s

_deps/lua-src/llex.o: _deps/lua-src/llex.c.o
.PHONY : _deps/lua-src/llex.o

# target to build an object file
_deps/lua-src/llex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/llex.c.o
.PHONY : _deps/lua-src/llex.c.o

_deps/lua-src/llex.i: _deps/lua-src/llex.c.i
.PHONY : _deps/lua-src/llex.i

# target to preprocess a source file
_deps/lua-src/llex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/llex.c.i
.PHONY : _deps/lua-src/llex.c.i

_deps/lua-src/llex.s: _deps/lua-src/llex.c.s
.PHONY : _deps/lua-src/llex.s

# target to generate assembly for a file
_deps/lua-src/llex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/llex.c.s
.PHONY : _deps/lua-src/llex.c.s

_deps/lua-src/lmathlib.o: _deps/lua-src/lmathlib.c.o
.PHONY : _deps/lua-src/lmathlib.o

# target to build an object file
_deps/lua-src/lmathlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lmathlib.c.o
.PHONY : _deps/lua-src/lmathlib.c.o

_deps/lua-src/lmathlib.i: _deps/lua-src/lmathlib.c.i
.PHONY : _deps/lua-src/lmathlib.i

# target to preprocess a source file
_deps/lua-src/lmathlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lmathlib.c.i
.PHONY : _deps/lua-src/lmathlib.c.i

_deps/lua-src/lmathlib.s: _deps/lua-src/lmathlib.c.s
.PHONY : _deps/lua-src/lmathlib.s

# target to generate assembly for a file
_deps/lua-src/lmathlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lmathlib.c.s
.PHONY : _deps/lua-src/lmathlib.c.s

_deps/lua-src/lmem.o: _deps/lua-src/lmem.c.o
.PHONY : _deps/lua-src/lmem.o

# target to build an object file
_deps/lua-src/lmem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lmem.c.o
.PHONY : _deps/lua-src/lmem.c.o

_deps/lua-src/lmem.i: _deps/lua-src/lmem.c.i
.PHONY : _deps/lua-src/lmem.i

# target to preprocess a source file
_deps/lua-src/lmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lmem.c.i
.PHONY : _deps/lua-src/lmem.c.i

_deps/lua-src/lmem.s: _deps/lua-src/lmem.c.s
.PHONY : _deps/lua-src/lmem.s

# target to generate assembly for a file
_deps/lua-src/lmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lmem.c.s
.PHONY : _deps/lua-src/lmem.c.s

_deps/lua-src/loadlib.o: _deps/lua-src/loadlib.c.o
.PHONY : _deps/lua-src/loadlib.o

# target to build an object file
_deps/lua-src/loadlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/loadlib.c.o
.PHONY : _deps/lua-src/loadlib.c.o

_deps/lua-src/loadlib.i: _deps/lua-src/loadlib.c.i
.PHONY : _deps/lua-src/loadlib.i

# target to preprocess a source file
_deps/lua-src/loadlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/loadlib.c.i
.PHONY : _deps/lua-src/loadlib.c.i

_deps/lua-src/loadlib.s: _deps/lua-src/loadlib.c.s
.PHONY : _deps/lua-src/loadlib.s

# target to generate assembly for a file
_deps/lua-src/loadlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/loadlib.c.s
.PHONY : _deps/lua-src/loadlib.c.s

_deps/lua-src/lobject.o: _deps/lua-src/lobject.c.o
.PHONY : _deps/lua-src/lobject.o

# target to build an object file
_deps/lua-src/lobject.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lobject.c.o
.PHONY : _deps/lua-src/lobject.c.o

_deps/lua-src/lobject.i: _deps/lua-src/lobject.c.i
.PHONY : _deps/lua-src/lobject.i

# target to preprocess a source file
_deps/lua-src/lobject.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lobject.c.i
.PHONY : _deps/lua-src/lobject.c.i

_deps/lua-src/lobject.s: _deps/lua-src/lobject.c.s
.PHONY : _deps/lua-src/lobject.s

# target to generate assembly for a file
_deps/lua-src/lobject.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lobject.c.s
.PHONY : _deps/lua-src/lobject.c.s

_deps/lua-src/lopcodes.o: _deps/lua-src/lopcodes.c.o
.PHONY : _deps/lua-src/lopcodes.o

# target to build an object file
_deps/lua-src/lopcodes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lopcodes.c.o
.PHONY : _deps/lua-src/lopcodes.c.o

_deps/lua-src/lopcodes.i: _deps/lua-src/lopcodes.c.i
.PHONY : _deps/lua-src/lopcodes.i

# target to preprocess a source file
_deps/lua-src/lopcodes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lopcodes.c.i
.PHONY : _deps/lua-src/lopcodes.c.i

_deps/lua-src/lopcodes.s: _deps/lua-src/lopcodes.c.s
.PHONY : _deps/lua-src/lopcodes.s

# target to generate assembly for a file
_deps/lua-src/lopcodes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lopcodes.c.s
.PHONY : _deps/lua-src/lopcodes.c.s

_deps/lua-src/loslib.o: _deps/lua-src/loslib.c.o
.PHONY : _deps/lua-src/loslib.o

# target to build an object file
_deps/lua-src/loslib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/loslib.c.o
.PHONY : _deps/lua-src/loslib.c.o

_deps/lua-src/loslib.i: _deps/lua-src/loslib.c.i
.PHONY : _deps/lua-src/loslib.i

# target to preprocess a source file
_deps/lua-src/loslib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/loslib.c.i
.PHONY : _deps/lua-src/loslib.c.i

_deps/lua-src/loslib.s: _deps/lua-src/loslib.c.s
.PHONY : _deps/lua-src/loslib.s

# target to generate assembly for a file
_deps/lua-src/loslib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/loslib.c.s
.PHONY : _deps/lua-src/loslib.c.s

_deps/lua-src/lparser.o: _deps/lua-src/lparser.c.o
.PHONY : _deps/lua-src/lparser.o

# target to build an object file
_deps/lua-src/lparser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lparser.c.o
.PHONY : _deps/lua-src/lparser.c.o

_deps/lua-src/lparser.i: _deps/lua-src/lparser.c.i
.PHONY : _deps/lua-src/lparser.i

# target to preprocess a source file
_deps/lua-src/lparser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lparser.c.i
.PHONY : _deps/lua-src/lparser.c.i

_deps/lua-src/lparser.s: _deps/lua-src/lparser.c.s
.PHONY : _deps/lua-src/lparser.s

# target to generate assembly for a file
_deps/lua-src/lparser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lparser.c.s
.PHONY : _deps/lua-src/lparser.c.s

_deps/lua-src/lstate.o: _deps/lua-src/lstate.c.o
.PHONY : _deps/lua-src/lstate.o

# target to build an object file
_deps/lua-src/lstate.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lstate.c.o
.PHONY : _deps/lua-src/lstate.c.o

_deps/lua-src/lstate.i: _deps/lua-src/lstate.c.i
.PHONY : _deps/lua-src/lstate.i

# target to preprocess a source file
_deps/lua-src/lstate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lstate.c.i
.PHONY : _deps/lua-src/lstate.c.i

_deps/lua-src/lstate.s: _deps/lua-src/lstate.c.s
.PHONY : _deps/lua-src/lstate.s

# target to generate assembly for a file
_deps/lua-src/lstate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lstate.c.s
.PHONY : _deps/lua-src/lstate.c.s

_deps/lua-src/lstring.o: _deps/lua-src/lstring.c.o
.PHONY : _deps/lua-src/lstring.o

# target to build an object file
_deps/lua-src/lstring.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lstring.c.o
.PHONY : _deps/lua-src/lstring.c.o

_deps/lua-src/lstring.i: _deps/lua-src/lstring.c.i
.PHONY : _deps/lua-src/lstring.i

# target to preprocess a source file
_deps/lua-src/lstring.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lstring.c.i
.PHONY : _deps/lua-src/lstring.c.i

_deps/lua-src/lstring.s: _deps/lua-src/lstring.c.s
.PHONY : _deps/lua-src/lstring.s

# target to generate assembly for a file
_deps/lua-src/lstring.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lstring.c.s
.PHONY : _deps/lua-src/lstring.c.s

_deps/lua-src/lstrlib.o: _deps/lua-src/lstrlib.c.o
.PHONY : _deps/lua-src/lstrlib.o

# target to build an object file
_deps/lua-src/lstrlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lstrlib.c.o
.PHONY : _deps/lua-src/lstrlib.c.o

_deps/lua-src/lstrlib.i: _deps/lua-src/lstrlib.c.i
.PHONY : _deps/lua-src/lstrlib.i

# target to preprocess a source file
_deps/lua-src/lstrlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lstrlib.c.i
.PHONY : _deps/lua-src/lstrlib.c.i

_deps/lua-src/lstrlib.s: _deps/lua-src/lstrlib.c.s
.PHONY : _deps/lua-src/lstrlib.s

# target to generate assembly for a file
_deps/lua-src/lstrlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lstrlib.c.s
.PHONY : _deps/lua-src/lstrlib.c.s

_deps/lua-src/ltable.o: _deps/lua-src/ltable.c.o
.PHONY : _deps/lua-src/ltable.o

# target to build an object file
_deps/lua-src/ltable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ltable.c.o
.PHONY : _deps/lua-src/ltable.c.o

_deps/lua-src/ltable.i: _deps/lua-src/ltable.c.i
.PHONY : _deps/lua-src/ltable.i

# target to preprocess a source file
_deps/lua-src/ltable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ltable.c.i
.PHONY : _deps/lua-src/ltable.c.i

_deps/lua-src/ltable.s: _deps/lua-src/ltable.c.s
.PHONY : _deps/lua-src/ltable.s

# target to generate assembly for a file
_deps/lua-src/ltable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ltable.c.s
.PHONY : _deps/lua-src/ltable.c.s

_deps/lua-src/ltablib.o: _deps/lua-src/ltablib.c.o
.PHONY : _deps/lua-src/ltablib.o

# target to build an object file
_deps/lua-src/ltablib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ltablib.c.o
.PHONY : _deps/lua-src/ltablib.c.o

_deps/lua-src/ltablib.i: _deps/lua-src/ltablib.c.i
.PHONY : _deps/lua-src/ltablib.i

# target to preprocess a source file
_deps/lua-src/ltablib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ltablib.c.i
.PHONY : _deps/lua-src/ltablib.c.i

_deps/lua-src/ltablib.s: _deps/lua-src/ltablib.c.s
.PHONY : _deps/lua-src/ltablib.s

# target to generate assembly for a file
_deps/lua-src/ltablib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ltablib.c.s
.PHONY : _deps/lua-src/ltablib.c.s

_deps/lua-src/ltm.o: _deps/lua-src/ltm.c.o
.PHONY : _deps/lua-src/ltm.o

# target to build an object file
_deps/lua-src/ltm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ltm.c.o
.PHONY : _deps/lua-src/ltm.c.o

_deps/lua-src/ltm.i: _deps/lua-src/ltm.c.i
.PHONY : _deps/lua-src/ltm.i

# target to preprocess a source file
_deps/lua-src/ltm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ltm.c.i
.PHONY : _deps/lua-src/ltm.c.i

_deps/lua-src/ltm.s: _deps/lua-src/ltm.c.s
.PHONY : _deps/lua-src/ltm.s

# target to generate assembly for a file
_deps/lua-src/ltm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/ltm.c.s
.PHONY : _deps/lua-src/ltm.c.s

_deps/lua-src/lundump.o: _deps/lua-src/lundump.c.o
.PHONY : _deps/lua-src/lundump.o

# target to build an object file
_deps/lua-src/lundump.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lundump.c.o
.PHONY : _deps/lua-src/lundump.c.o

_deps/lua-src/lundump.i: _deps/lua-src/lundump.c.i
.PHONY : _deps/lua-src/lundump.i

# target to preprocess a source file
_deps/lua-src/lundump.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lundump.c.i
.PHONY : _deps/lua-src/lundump.c.i

_deps/lua-src/lundump.s: _deps/lua-src/lundump.c.s
.PHONY : _deps/lua-src/lundump.s

# target to generate assembly for a file
_deps/lua-src/lundump.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lundump.c.s
.PHONY : _deps/lua-src/lundump.c.s

_deps/lua-src/lutf8lib.o: _deps/lua-src/lutf8lib.c.o
.PHONY : _deps/lua-src/lutf8lib.o

# target to build an object file
_deps/lua-src/lutf8lib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lutf8lib.c.o
.PHONY : _deps/lua-src/lutf8lib.c.o

_deps/lua-src/lutf8lib.i: _deps/lua-src/lutf8lib.c.i
.PHONY : _deps/lua-src/lutf8lib.i

# target to preprocess a source file
_deps/lua-src/lutf8lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lutf8lib.c.i
.PHONY : _deps/lua-src/lutf8lib.c.i

_deps/lua-src/lutf8lib.s: _deps/lua-src/lutf8lib.c.s
.PHONY : _deps/lua-src/lutf8lib.s

# target to generate assembly for a file
_deps/lua-src/lutf8lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lutf8lib.c.s
.PHONY : _deps/lua-src/lutf8lib.c.s

_deps/lua-src/lvm.o: _deps/lua-src/lvm.c.o
.PHONY : _deps/lua-src/lvm.o

# target to build an object file
_deps/lua-src/lvm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lvm.c.o
.PHONY : _deps/lua-src/lvm.c.o

_deps/lua-src/lvm.i: _deps/lua-src/lvm.c.i
.PHONY : _deps/lua-src/lvm.i

# target to preprocess a source file
_deps/lua-src/lvm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lvm.c.i
.PHONY : _deps/lua-src/lvm.c.i

_deps/lua-src/lvm.s: _deps/lua-src/lvm.c.s
.PHONY : _deps/lua-src/lvm.s

# target to generate assembly for a file
_deps/lua-src/lvm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lvm.c.s
.PHONY : _deps/lua-src/lvm.c.s

_deps/lua-src/lzio.o: _deps/lua-src/lzio.c.o
.PHONY : _deps/lua-src/lzio.o

# target to build an object file
_deps/lua-src/lzio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lzio.c.o
.PHONY : _deps/lua-src/lzio.c.o

_deps/lua-src/lzio.i: _deps/lua-src/lzio.c.i
.PHONY : _deps/lua-src/lzio.i

# target to preprocess a source file
_deps/lua-src/lzio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lzio.c.i
.PHONY : _deps/lua-src/lzio.c.i

_deps/lua-src/lzio.s: _deps/lua-src/lzio.c.s
.PHONY : _deps/lua-src/lzio.s

# target to generate assembly for a file
_deps/lua-src/lzio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lua_static.dir/build.make CMakeFiles/lua_static.dir/_deps/lua-src/lzio.c.s
.PHONY : _deps/lua-src/lzio.c.s

src/core/Game.o: src/core/Game.cpp.o
.PHONY : src/core/Game.o

# target to build an object file
src/core/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/src/core/Game.cpp.o
.PHONY : src/core/Game.cpp.o

src/core/Game.i: src/core/Game.cpp.i
.PHONY : src/core/Game.i

# target to preprocess a source file
src/core/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/src/core/Game.cpp.i
.PHONY : src/core/Game.cpp.i

src/core/Game.s: src/core/Game.cpp.s
.PHONY : src/core/Game.s

# target to generate assembly for a file
src/core/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/src/core/Game.cpp.s
.PHONY : src/core/Game.cpp.s

src/ecs/World.o: src/ecs/World.cpp.o
.PHONY : src/ecs/World.o

# target to build an object file
src/ecs/World.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/src/ecs/World.cpp.o
.PHONY : src/ecs/World.cpp.o

src/ecs/World.i: src/ecs/World.cpp.i
.PHONY : src/ecs/World.i

# target to preprocess a source file
src/ecs/World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/src/ecs/World.cpp.i
.PHONY : src/ecs/World.cpp.i

src/ecs/World.s: src/ecs/World.cpp.s
.PHONY : src/ecs/World.s

# target to generate assembly for a file
src/ecs/World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/src/ecs/World.cpp.s
.PHONY : src/ecs/World.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/scripting/ScriptingEngine.o: src/scripting/ScriptingEngine.cpp.o
.PHONY : src/scripting/ScriptingEngine.o

# target to build an object file
src/scripting/ScriptingEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/src/scripting/ScriptingEngine.cpp.o
.PHONY : src/scripting/ScriptingEngine.cpp.o

src/scripting/ScriptingEngine.i: src/scripting/ScriptingEngine.cpp.i
.PHONY : src/scripting/ScriptingEngine.i

# target to preprocess a source file
src/scripting/ScriptingEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/src/scripting/ScriptingEngine.cpp.i
.PHONY : src/scripting/ScriptingEngine.cpp.i

src/scripting/ScriptingEngine.s: src/scripting/ScriptingEngine.cpp.s
.PHONY : src/scripting/ScriptingEngine.s

# target to generate assembly for a file
src/scripting/ScriptingEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2d-engine.dir/build.make CMakeFiles/2d-engine.dir/src/scripting/ScriptingEngine.cpp.s
.PHONY : src/scripting/ScriptingEngine.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... 2d-engine"
	@echo "... SDL3-shared"
	@echo "... SDL3_test"
	@echo "... SDL_uclibc"
	@echo "... glm"
	@echo "... lua_static"
	@echo "... _deps/lua-src/lapi.o"
	@echo "... _deps/lua-src/lapi.i"
	@echo "... _deps/lua-src/lapi.s"
	@echo "... _deps/lua-src/lauxlib.o"
	@echo "... _deps/lua-src/lauxlib.i"
	@echo "... _deps/lua-src/lauxlib.s"
	@echo "... _deps/lua-src/lbaselib.o"
	@echo "... _deps/lua-src/lbaselib.i"
	@echo "... _deps/lua-src/lbaselib.s"
	@echo "... _deps/lua-src/lcode.o"
	@echo "... _deps/lua-src/lcode.i"
	@echo "... _deps/lua-src/lcode.s"
	@echo "... _deps/lua-src/lcorolib.o"
	@echo "... _deps/lua-src/lcorolib.i"
	@echo "... _deps/lua-src/lcorolib.s"
	@echo "... _deps/lua-src/lctype.o"
	@echo "... _deps/lua-src/lctype.i"
	@echo "... _deps/lua-src/lctype.s"
	@echo "... _deps/lua-src/ldblib.o"
	@echo "... _deps/lua-src/ldblib.i"
	@echo "... _deps/lua-src/ldblib.s"
	@echo "... _deps/lua-src/ldebug.o"
	@echo "... _deps/lua-src/ldebug.i"
	@echo "... _deps/lua-src/ldebug.s"
	@echo "... _deps/lua-src/ldo.o"
	@echo "... _deps/lua-src/ldo.i"
	@echo "... _deps/lua-src/ldo.s"
	@echo "... _deps/lua-src/ldump.o"
	@echo "... _deps/lua-src/ldump.i"
	@echo "... _deps/lua-src/ldump.s"
	@echo "... _deps/lua-src/lfunc.o"
	@echo "... _deps/lua-src/lfunc.i"
	@echo "... _deps/lua-src/lfunc.s"
	@echo "... _deps/lua-src/lgc.o"
	@echo "... _deps/lua-src/lgc.i"
	@echo "... _deps/lua-src/lgc.s"
	@echo "... _deps/lua-src/linit.o"
	@echo "... _deps/lua-src/linit.i"
	@echo "... _deps/lua-src/linit.s"
	@echo "... _deps/lua-src/liolib.o"
	@echo "... _deps/lua-src/liolib.i"
	@echo "... _deps/lua-src/liolib.s"
	@echo "... _deps/lua-src/llex.o"
	@echo "... _deps/lua-src/llex.i"
	@echo "... _deps/lua-src/llex.s"
	@echo "... _deps/lua-src/lmathlib.o"
	@echo "... _deps/lua-src/lmathlib.i"
	@echo "... _deps/lua-src/lmathlib.s"
	@echo "... _deps/lua-src/lmem.o"
	@echo "... _deps/lua-src/lmem.i"
	@echo "... _deps/lua-src/lmem.s"
	@echo "... _deps/lua-src/loadlib.o"
	@echo "... _deps/lua-src/loadlib.i"
	@echo "... _deps/lua-src/loadlib.s"
	@echo "... _deps/lua-src/lobject.o"
	@echo "... _deps/lua-src/lobject.i"
	@echo "... _deps/lua-src/lobject.s"
	@echo "... _deps/lua-src/lopcodes.o"
	@echo "... _deps/lua-src/lopcodes.i"
	@echo "... _deps/lua-src/lopcodes.s"
	@echo "... _deps/lua-src/loslib.o"
	@echo "... _deps/lua-src/loslib.i"
	@echo "... _deps/lua-src/loslib.s"
	@echo "... _deps/lua-src/lparser.o"
	@echo "... _deps/lua-src/lparser.i"
	@echo "... _deps/lua-src/lparser.s"
	@echo "... _deps/lua-src/lstate.o"
	@echo "... _deps/lua-src/lstate.i"
	@echo "... _deps/lua-src/lstate.s"
	@echo "... _deps/lua-src/lstring.o"
	@echo "... _deps/lua-src/lstring.i"
	@echo "... _deps/lua-src/lstring.s"
	@echo "... _deps/lua-src/lstrlib.o"
	@echo "... _deps/lua-src/lstrlib.i"
	@echo "... _deps/lua-src/lstrlib.s"
	@echo "... _deps/lua-src/ltable.o"
	@echo "... _deps/lua-src/ltable.i"
	@echo "... _deps/lua-src/ltable.s"
	@echo "... _deps/lua-src/ltablib.o"
	@echo "... _deps/lua-src/ltablib.i"
	@echo "... _deps/lua-src/ltablib.s"
	@echo "... _deps/lua-src/ltm.o"
	@echo "... _deps/lua-src/ltm.i"
	@echo "... _deps/lua-src/ltm.s"
	@echo "... _deps/lua-src/lundump.o"
	@echo "... _deps/lua-src/lundump.i"
	@echo "... _deps/lua-src/lundump.s"
	@echo "... _deps/lua-src/lutf8lib.o"
	@echo "... _deps/lua-src/lutf8lib.i"
	@echo "... _deps/lua-src/lutf8lib.s"
	@echo "... _deps/lua-src/lvm.o"
	@echo "... _deps/lua-src/lvm.i"
	@echo "... _deps/lua-src/lvm.s"
	@echo "... _deps/lua-src/lzio.o"
	@echo "... _deps/lua-src/lzio.i"
	@echo "... _deps/lua-src/lzio.s"
	@echo "... src/core/Game.o"
	@echo "... src/core/Game.i"
	@echo "... src/core/Game.s"
	@echo "... src/ecs/World.o"
	@echo "... src/ecs/World.i"
	@echo "... src/ecs/World.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/scripting/ScriptingEngine.o"
	@echo "... src/scripting/ScriptingEngine.i"
	@echo "... src/scripting/ScriptingEngine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/itziar/dev/engine2d/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

