# cmake/EmbedScriptRun.cmake
# Invoked by add_custom_command at build time (not configure time).
# Variables passed via -D: LUA_PATH, OUT_FILE, VAR_NAME

file(READ "${LUA_PATH}" RAW_CONTENT)

# Escape backslashes, then double-quotes, then newlines for a C string literal.
string(REPLACE "\\" "\\\\" ESCAPED "${RAW_CONTENT}")
string(REPLACE "\"" "\\\"" ESCAPED "${ESCAPED}")
string(REPLACE "\n" "\\n"  ESCAPED "${ESCAPED}")

file(WRITE "${OUT_FILE}"
"#pragma once
// Auto-generated by cmake/EmbedScriptRun.cmake -- do not edit.
namespace embedded {
inline constexpr char ${VAR_NAME}[] = \"${ESCAPED}\";
} // namespace embedded
"
)
